apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-auth-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "external-auth-server.name" . }}
    helm.sh/chart: {{ include "external-auth-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  config-token-sign-secret: {{ required "configTokenSignSecret is required" .Values.configTokenSignSecret | b64enc | quote }}
  config-token-encrypt-secret: {{ required "configTokenEncryptSecret is required" .Values.configTokenEncryptSecret | b64enc | quote }}
  issuer-sign-secret: {{ required "issuerSignSecret is required" .Values.issuerSignSecret | b64enc | quote }}
  issuer-encrypt-secret: {{ required "issuerEncryptSecret is required" .Values.issuerEncryptSecret | b64enc | quote }}
  cookie-sign-secret: {{ required "cookieSignSecret is required" .Values.cookieSignSecret | b64enc | quote }}
  cookie-encrypt-secret: {{ required "cookieEncryptSecret is required" .Values.cookieEncryptSecret | b64enc | quote }}
  session-encrypt-secret: {{ required "sessionEncryptSecret is required" .Values.sessionEncryptSecret | b64enc | quote }}
  {{- if .Values.storeOpts }}
  store-opts: {{ .Values.storeOpts | toJson | b64enc | quote }}
  {{- end }}
  {{- if .Values.configTokenStores }}
  config-token-stores: {{ .Values.configTokenStores | toJson | b64enc | quote }}
  {{- end }}
  {{- if .Values.configTokens }}
  config-tokens: {{ .Values.configTokens | toJson | b64enc | quote }}
  {{- end }}
  {{- if .Values.backchannelLogoutConfig }}
  backchannel-logout-config: {{ .Values.backchannelLogoutConfig | toJson | b64enc | quote }}
  {{- end }}

